# Generated by Django 5.1.5 on 2025-02-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address_mobile_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile',
            new_name='phone',
        ),
    ]
